# Generated by Django 5.0.6 on 2025-05-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userbankaccount_bank_rupt'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='street_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
